[package]
name = "nubuild"
version = "0.1.0"
edition = "2021"
description = "Abstracts away build systems."
authors = ["Alexander Roper"]

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
